version: '3.8'
services:
  duntasks:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=7373
    env_file:
      - .env
    ports:
      - '7373:7373'
    restart: unless-stopped
