version: '3.8'
services:
  duntasks:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - '3000' # internal only; Caddy will proxy to this
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true

volumes:
  caddy_data:
  caddy_config:
